"""initial schema

Revision ID: 445220194188
Revises: 
Create Date: 2026-09-18 01:57:31.193236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445220194188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('retention_category', sa.String(length=100), nullable=False),
    sa.Column('metadata_fields', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retention_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('auto_delete', sa.Boolean(), nullable=False),
    sa.Column('auto_archive_after_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'LEGAL', 'INVESTIGATOR', 'EXTERNAL', name='userrole'), nullable=False),
    sa.Column('organisation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata_fields', sa.JSON(), nullable=False),
    sa.Column('linked_folder_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_case_id'), 'folders', ['case_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('VIDEO', 'FOLDER', name='shareresourcetype'), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.Enum('VIEW_ONLY', 'DOWNLOAD', name='sharescope'), nullable=False),
    sa.Column('recipient_type', sa.Enum('INTERNAL_STAFF', 'LEGAL_TEAM', 'POLICE', 'INSURANCE', 'COURT', 'FOI', 'GUEST', name='recipienttype'), nullable=False),
    sa.Column('recipient_label', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_resource_id'), 'share_links', ['resource_id'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.create_table('watermarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'USER', name='watermarkscope'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('template', sa.String(length=500), nullable=False),
    sa.Column('enabled_for_playback', sa.Boolean(), nullable=False),
    sa.Column('enabled_for_export', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_permissions_folder_id'), 'folder_permissions', ['folder_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('source_connector', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('INGESTED', 'PROCESSING', 'READY', 'NEEDS_VENDOR_DECODER', 'FAILED', 'DELETED', name='videostatus'), nullable=False),
    sa.Column('storage_tier', sa.Enum('HOT', 'COLD', 'RESTORING', name='storagetier'), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('metadata_fields', sa.JSON(), nullable=False),
    sa.Column('retention_category', sa.String(length=100), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_folder_id'), 'videos', ['folder_id'], unique=False)
    op.create_table('storage_tier_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('HOT', 'COLD', 'RESTORING', name='storagetier'), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('restore_eta', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_tier_events_video_id'), 'storage_tier_events', ['video_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_video_id'), 'transcripts', ['video_id'], unique=True)
    op.create_table('video_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('ORIGINAL', 'REDACTED', 'DISCLOSURE', name='videoversionkind'), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('storage_tier', sa.Enum('HOT', 'COLD', 'RESTORING', name='storagetier'), nullable=False),
    sa.Column('redaction_job_id', sa.Uuid(), nullable=True),
    sa.Column('watermark_applied', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['video_versions.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_versions_video_id'), 'video_versions', ['video_id'], unique=False)
    op.create_table('redaction_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('FACE_AUTO', 'FACE_TRACKED', 'MANUAL_REGION', 'AUDIO_MUTE', 'TRANSCRIPT_BASED_AUDIO', name='redactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', name='redactionjobstatus'), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=False),
    sa.Column('audio_segments', sa.JSON(), nullable=False),
    sa.Column('result_version_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_version_id'], ['video_versions.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['video_versions.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redaction_jobs_video_id'), 'redaction_jobs', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redaction_jobs_video_id'), table_name='redaction_jobs')
    op.drop_table('redaction_jobs')
    op.drop_index(op.f('ix_video_versions_video_id'), table_name='video_versions')
    op.drop_table('video_versions')
    op.drop_index(op.f('ix_transcripts_video_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_storage_tier_events_video_id'), table_name='storage_tier_events')
    op.drop_table('storage_tier_events')
    op.drop_index(op.f('ix_videos_folder_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_folder_permissions_folder_id'), table_name='folder_permissions')
    op.drop_table('folder_permissions')
    op.drop_table('watermarks')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_resource_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_folders_case_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('retention_policies')
    op.drop_table('cases')
    # ### end Alembic commands ###
